spring.application.name=dataService

#Service configuration
server.port=8080

#RabbitMQ configuration
#spring.rabbitmq.host=${RABBITMQ_HOST:}
#spring.rabbitmq.port=${RABBITMQ_PORT:}
#spring.rabbitmq.username=${RABBITMQ_USERNAME:}
#spring.rabbitmq.password=${RABBITMQ_PASSWORD:}
#spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:}